-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
B.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM ONLINE_SALE A 
JOIN USER_INFO B ON A.USER_ID = B.USER_ID 
WHERE B.GENDER IS NOT NULL 
GROUP BY 1,2,3
ORDER BY 1 ASC, 2 ASC, 3 ASC